sudo: required
services: 
  - docker

before_install:
  - docker build -t ahmetilhann/kubernetes-react-example -f Dockerfile.dev .

script:
  - docker run ahmetilhann/kubernetes-react-example npm run test -- --coverage